import React, { useEffect, useRef, useState } from 'react';
import { Bot, Cpu, Send, Timer, Trash2, User } from 'lucide-react';
import { PageHeader, Spinner } from '../ui/primitives';
import { useToast } from '../ui/toast';
import { api } from '../services/api';
import { formatDuration } from '../lib/format';
import type { ChatMessage } from '../types/api';

const SUGGESTIONS = [
  'What is the procedure for replacing a corroded high-pressure control valve?',
  'Walk me through the lock-out/tag-out steps for electrical isolation.',
  'What wall-thickness threshold triggers pipe replacement during corrosion inspection?',
  'Calculate pump efficiency for a flow of 50 m3/h, 60 m head and 11 kW input.',
  'When must shell-and-tube heat exchanger tubes be plugged?',
];

interface Turn {
  role: 'user' | 'assistant';
  content: string;
  model?: string;
  taskType?: string | null;
  durationMs?: number;
}

export const Assistant: React.FC = () => {
  const toast = useToast();
  const [turns, setTurns] = useState<Turn[]>([]);
  const [draft, setDraft] = useState('');
  const [sending, setSending] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [turns, sending]);

  const send = async () => {
    const text = draft.trim();
    if (!text || sending) return;

    const nextTurns: Turn[] = [...turns, { role: 'user', content: text }];
    setTurns(nextTurns);
    setDraft('');
    setSending(true);

    try {
      const history: ChatMessage[] = nextTurns.map((turn) => ({
        role: turn.role,
        content: turn.content,
      }));

      const response = await api.chatConversation({ messages: history, auto_route: true });

      setTurns((current) => [
        ...current,
        {
          role: 'assistant',
          content: response.reply,
          model: response.model,
          taskType: response.task_type,
          durationMs: response.duration_ms,
        },
      ]);
    } catch (error) {
      toast.error(`Assistant unavailable: ${(error as Error).message}`);
      setTurns((current) => [
        ...current,
        {
          role: 'assistant',
          content:
            'The local model did not respond. Check that Ollama is running, then send the message again.',
        },
      ]);
    } finally {
      setSending(false);
      inputRef.current?.focus();
    }
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      send();
    }
  };

  return (
    <>
      <PageHeader
        title="Assistant"
        subtitle="A conversational view onto the same local models the agent uses. Nothing typed here leaves the machine."
        actions={
          turns.length > 0 ? (
            <button type="button" className="btn btn-secondary" onClick={() => setTurns([])}>
              <Trash2 size={14} />
              Clear conversation
            </button>
          ) : undefined
        }
      />

      <div className="chat-shell">
        <div className="chat-log">
          {turns.length === 0 ? (
            <div className="stack gap-20" style={{ margin: 'auto', maxWidth: 560, width: '100%' }}>
              <div className="stack gap-4" style={{ textAlign: 'center' }}>
                <span className="empty-icon" style={{ margin: '0 auto' }}>
                  <Bot size={20} />
                </span>
                <p className="empty-title">Ask about a procedure or a calculation</p>
                <p className="empty-text" style={{ margin: '0 auto' }}>
                  Answers are generated by the open-weight models installed on this host and
                  grounded in the local knowledge base.
                </p>
              </div>

              <div className="stack gap-6">
                <p className="eyebrow">Try one of these</p>
                {SUGGESTIONS.map((suggestion) => (
                  <button
                    key={suggestion}
                    type="button"
                    className="panel panel-plain"
                    style={{ textAlign: 'left', cursor: 'pointer', fontSize: 13 }}
                    onClick={() => {
                      setDraft(suggestion);
                      inputRef.current?.focus();
                    }}
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            turns.map((turn, index) => (
              <div key={index} className={`chat-turn${turn.role === 'user' ? ' is-user' : ''}`}>
                <span className="chat-avatar" aria-hidden>
                  {turn.role === 'user' ? <User size={15} /> : <Bot size={15} />}
                </span>
                <div className="chat-bubble">
                  {turn.content}
                  {turn.role === 'assistant' && (turn.model || turn.durationMs !== undefined) && (
                    <div className="chat-meta">
                      {turn.model && (
                        <span className="row gap-4">
                          <Cpu size={11} />
                          <span className="mono">{turn.model}</span>
                        </span>
                      )}
                      {turn.taskType && <span className="badge badge-brand">{turn.taskType}</span>}
                      {turn.durationMs !== undefined && (
                        <span className="row gap-4">
                          <Timer size={11} />
                          {formatDuration(turn.durationMs)}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))
          )}

          {sending && (
            <div className="chat-turn">
              <span className="chat-avatar" aria-hidden>
                <Bot size={15} />
              </span>
              <div className="chat-bubble">
                <Spinner size={14} label="Generating on the local model…" />
              </div>
            </div>
          )}

          <div ref={endRef} />
        </div>

        <div className="chat-composer">
          <label className="sr-only" htmlFor="assistant-input">
            Message
          </label>
          <textarea
            id="assistant-input"
            ref={inputRef}
            className="textarea"
            rows={2}
            style={{ minHeight: 44 }}
            placeholder="Ask a question — Enter to send, Shift+Enter for a new line"
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={handleKeyDown}
            disabled={sending}
          />
          <button
            type="button"
            className="btn btn-primary"
            onClick={send}
            disabled={!draft.trim() || sending}
            style={{ height: 44 }}
            aria-label="Send message"
          >
            <Send size={16} />
          </button>
        </div>
      </div>
    </>
  );
};
